web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"